version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  api:
    container_name: api
    build: API
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./API:/code
    ports:
      - "80:80"
    depends_on:
      - db
  ui:
    container_name: ui
    build: UI
    ports:
      - "8080:80"