# Generated by Django 3.1.7 on 2021-03-07 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('street', models.CharField(max_length=50, verbose_name='Street/Road')),
                ('county', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu'), ('Mombasa', 'Mombasa')], max_length=50)),
                ('sub_county', models.CharField(choices=[], max_length=50)),
                ('ward', models.CharField(choices=[], max_length=50)),
                ('location', models.CharField(max_length=50, verbose_name='geolocation')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companys',
            },
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(max_length=50, verbose_name='type of waste')),
                ('disposal_mechanism', models.CharField(max_length=50, verbose_name='Waste disposal mechanism.')),
                ('potential_hazard', models.CharField(max_length=50, verbose_name='potential hazard')),
                ('eia', models.BinaryField(verbose_name='Environmental impact assessment.')),
                ('air_quality', models.CharField(max_length=50, verbose_name='air quality')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firm.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Waste',
                'verbose_name_plural': 'Wastes',
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(max_length=50, verbose_name='Type of goods produced.')),
                ('technology', models.CharField(max_length=50, verbose_name='Technology')),
                ('size', models.CharField(max_length=50, verbose_name='size')),
                ('sourced_nearby', models.BooleanField(verbose_name='Are raw materials sourced nearby.')),
                ('raw_materials', models.CharField(max_length=50, verbose_name='the raw materials.')),
                ('products', models.CharField(max_length=50, verbose_name='Finished products.')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firm.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Activities',
                'verbose_name_plural': 'Activitiess',
            },
        ),
    ]
